# Generated by Django 5.2.13 on 2026-05-26 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_joboffer_alter_adminprofile_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='education',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='experience',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='skills',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='jobs/'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='location',
            field=models.CharField(choices=[('remote', 'En ligne'), ('hybrid', 'Hybride'), ('onsite', 'En présentiel')], default='onsite', max_length=20),
        ),
    ]
