# Generated by Django 5.1.6 on 2025-03-03 23:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_userperso_alter_admin_user_delete_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userperso",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
