# Generated by Django 5.1.6 on 2025-03-04 16:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_alter_userperso_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="admin",
            name="permission",
            field=models.CharField(
                choices=[
                    ("read", "Read"),
                    ("create", "Create"),
                    ("delete", "Delete"),
                    ("manage", "Manage"),
                ],
                default="read",
                max_length=10,
            ),
        ),
    ]
