# Generated by Django 5.2.13 on 2026-05-26 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_jobapplication_education_jobapplication_experience_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='applicant_name',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='cover_letter',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='education',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='skills',
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='first_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='gender',
            field=models.CharField(choices=[('M', 'Homme'), ('F', 'Femme'), ('O', 'Autre')], default='O', max_length=10),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='last_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='phone',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='projects',
            field=models.TextField(blank=True, help_text='Décrivez le projet dont vous êtes le plus fier', null=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='resume',
            field=models.FileField(upload_to='resumes/'),
        ),
    ]
