# Generated by Django 5.1.6 on 2025-03-04 22:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_alter_admin_permission"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projects",
            name="status",
            field=models.CharField(max_length=20),
        ),
    ]
