# Generated by Django 5.2.13 on 2026-05-29 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_jobapplication_applicant_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='interview_link',
            field=models.URLField(blank=True, help_text="Lien pour l'entretien en ligne (Zoom, Meet, etc.)", null=True),
        ),
    ]
