# Generated by Django 5.2.13 on 2026-05-29 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_jobapplication_interview_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='reminder_1_day_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='reminder_20_min_sent',
            field=models.BooleanField(default=False),
        ),
    ]
