# Generated by Django 5.1.6 on 2025-03-09 11:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_alter_projects_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="admin",
            name="permission",
            field=models.CharField(
                choices=[
                    ("read", "Read"),
                    ("write", "Write"),
                    ("delete", "Delete"),
                    ("manage", "Manage"),
                ],
                default="read",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="projects",
            name="status",
            field=models.CharField(max_length=5),
        ),
    ]
