# Generated by Django 5.1.6 on 2025-03-09 19:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_alter_admin_permission_alter_projects_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, unique=True, verbose_name="Titre"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                ("slug", models.SlugField(blank=True, max_length=255, unique=True)),
                (
                    "last_updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Dernière mise à jour"
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "published",
                    models.BooleanField(default=False, verbose_name="Publié"),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True, upload_to="news/", verbose_name="Miniature"
                    ),
                ),
                ("content", models.TextField(verbose_name="Contenu")),
            ],
            options={
                "verbose_name": "Article",
                "verbose_name_plural": "Articles",
                "ordering": ["-created_on"],
            },
        ),
        migrations.AlterModelOptions(
            name="contact",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Contact",
                "verbose_name_plural": "Contacts",
            },
        ),
        migrations.RemoveField(
            model_name="admin",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="projects",
            name="created_at",
        ),
        migrations.AddField(
            model_name="contact",
            name="date_naissance",
            field=models.DateField(
                blank=True, null=True, verbose_name="Date de naissance"
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="telephone",
            field=models.CharField(
                blank=True,
                max_length=15,
                null=True,
                validators=[
                    django.core.validators.MinLengthValidator(10),
                    django.core.validators.RegexValidator(
                        message="Le numéro de téléphone doit être au format valide.",
                        regex="^\\+?1?\\d{9,15}$",
                    ),
                ],
                verbose_name="Téléphone",
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Date de création"
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="email",
            field=models.EmailField(max_length=50, verbose_name="Adresse email"),
        ),
        migrations.AlterField(
            model_name="contact",
            name="fullname",
            field=models.CharField(max_length=50, verbose_name="Nom complet"),
        ),
        migrations.AlterField(
            model_name="contact",
            name="message",
            field=models.TextField(verbose_name="Message"),
        ),
        migrations.AlterField(
            model_name="contact",
            name="sexe",
            field=models.CharField(
                blank=True,
                choices=[("M", "Masculin"), ("F", "Féminin"), ("O", "Autre")],
                max_length=1,
                null=True,
                verbose_name="Sexe",
            ),
        ),
        migrations.DeleteModel(
            name="Device",
        ),
    ]
