# Generated by Django 5.2.13 on 2026-05-29 15:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_jobapplication_reminder_1_day_sent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='joboffer',
            name='hr_managers',
            field=models.ManyToManyField(blank=True, limit_choices_to={'adminprofile__role': 'hr'}, related_name='managed_offers', to=settings.AUTH_USER_MODEL, verbose_name='RH assignés'),
        ),
        migrations.AlterField(
            model_name='adminprofile',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Admin'), ('community', 'Community Manager'), ('content', 'Content Manager'), ('hr', 'Ressources Humaines')], default='content', max_length=20),
        ),
    ]
