# Generated by Django 5.2.13 on 2026-05-30 06:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_joboffer_hr_managers_alter_adminprofile_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommercialTracker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nom')),
                ('target_company', models.CharField(max_length=150, verbose_name='Entreprise cible')),
                ('status', models.CharField(choices=[('prospection', 'Prospection'), ('rdv', 'RDV'), ('converti', 'Converti')], default='prospection', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
            ],
            options={
                'verbose_name': "Suivi Commercial / Apporteur d'affaires",
                'verbose_name_plural': "Suivi Commerciaux / Apporteurs d'affaires",
                'ordering': ['-created_at'],
            },
        ),
    ]
